apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: tonydoker/dapper:1.12
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dotnet-config
          mountPath: /app/config
#          subPath: appsettings.json
        #   - name: dotnet-secret
        #     mountPath: /app/secret 
        #     readOnly: true
      volumes:
        - name: dotnet-config
          configMap:
            name: dotnet-config-file
        - name: dotnet-secret
          secret:
            secretName: dotnet-secret-file 

