apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  labels:
    app: dotnet-app
spec:
  type: NodePort
  selector:
    app: dotnet-app
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80